### ISSUE TITLE
ChineseSimplified translation

### ISSUE THREAD

**Issue by Buyue-z** [emipa606/RepairingPriority#2]
<OpenRepairingPriorityDialog>打开修理优先级窗口。\n\n在这里，你可以设置殖民者优先修理建筑的区域、最后修理建筑的区域或介于两者之间的区域。</OpenRepairingPriorityDialog>
  <AddAreaAsRepairingArea>如果你对哪些区域内的建筑被优先修理感到困惑，请将鼠标悬停在列表中的区域上并阅读提示。</AddAreaAsRepairingArea>
  <AddAreaForPriorityRepairing>添加区域</AddAreaForPriorityRepairing>
  <AddAreaForPriorityRepairingTip>增加一个供殖民者修理的区域。</AddAreaForPriorityRepairingTip>
  <RepairingAreaIsPrioritized>殖民者将修理该区域内的建筑。</RepairingAreaIsPrioritized>
  <OnlyRepairingArea>仅该区域内的建筑将被修理。</OnlyRepairingArea>
  <RepairingAreaFirst>该区域内的建筑将优先被修理。</RepairingAreaFirst>
  <RepairingAreaLast>该区域内的建筑将最后被修理。</RepairingAreaLast>
  <RepairingAreaMiddle>该区域内的建筑将在{0}内的建筑之后，{1}内的建筑之前被修理。</RepairingAreaMiddle>

**Comment by emipa606** [comment]
Could you post this as a complete xml instead?

**Comment by Buyue-z** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LanguageData>
  <OpenRepairingPriorityDialog>打开修理优先级窗口。\n\n在这里，你可以设置殖民者优先修理建筑的区域、最后修理建筑的区域或介于两者之间的区域。</OpenRepairingPriorityDialog>
  <AddAreaAsRepairingArea>如果你对哪些区域内的建筑被优先修理感到困惑，请将鼠标悬停在列表中的区域上并阅读提示。</AddAreaAsRepairingArea>
  <AddAreaForPriorityRepairing>添加区域</AddAreaForPriorityRepairing>
  <AddAreaForPriorityRepairingTip>增加一个供殖民者修理的区域。</AddAreaForPriorityRepairingTip>
  <RepairingAreaIsPrioritized>殖民者将修理该区域内的建筑。</RepairingAreaIsPrioritized>
  <OnlyRepairingArea>仅该区域内的建筑将被修理。</OnlyRepairingArea>
  <RepairingAreaFirst>该区域内的建筑将优先被修理。</RepairingAreaFirst>
  <RepairingAreaLast>该区域内的建筑将最后被修理。</RepairingAreaLast>
  <RepairingAreaMiddle>该区域内的建筑将在{0}内的建筑之后，{1}内的建筑之前被修理。</RepairingAreaMiddle>
</LanguageData>`

**Comment by emipa606** [comment]
Thanks, should be published in 
25542bf
